/**
 * backend/utils/findingLibrary.js
 * 
 * ALFA X-RAY V3.0 — PROFESYONEL ZAFİYET KÜTÜPHANESİ
 * ------------------------------------------------
 * Bu kütüphane, her bir bulgu için akademik ve teknik düzeyde 
 * adli analiz verileri sağlar. Çift dil (TR/EN) desteği mevcuttur.
 */

export const FINDING_LIBRARY = {
  "hsts": {
    title: "HTTP Strict Transport Security (HSTS) Politikası Eksikliği",
    titleEn: "Missing HTTP Strict Transport Security (HSTS) Policy",
    severity: "Medium",
    cvss: 5.8,
    owasp: "A05:2021-Security Misconfiguration",
    description: "HSTS, web sitesinin tarayıcılara yalnızca HTTPS (güvenli) bağlantı üzerinden iletişim kurmasını emreden bir güvenlik mekanizmasıdır.",
    descriptionEn: "HSTS is a security mechanism that commands browsers to communicate with the website only over HTTPS (secure) connections.",
    technical: "Sunucu yanıtında 'Strict-Transport-Security' başlığı bulunamadı. Bu durum, ilk bağlantının güvensiz HTTP üzerinden yapılmasına izin verir.",
    technicalEn: "The 'Strict-Transport-Security' header was not found in the server response. This allows the initial connection to be made via insecure HTTP.",
    attack: "Saldırgan, 'SSL Stripping' yöntemini kullanarak kullanıcının HTTPS isteğini HTTP'ye düşürebilir ve araya girerek (MITM) verileri çalabilir.",
    attackEn: "An attacker could use 'SSL Stripping' to downgrade a user's HTTPS request to HTTP and intercept data (MITM).",
    impact: "Kullanıcı trafiği izlenebilir, oturum çerezleri ele geçirilebilir ve hassas veriler sızdırılabilir.",
    impactEn: "User traffic can be monitored, session cookies can be hijacked, and sensitive data can be leaked.",
    businessImpact: "ISO 27001 ve KVKK kapsamında 'Veri Gizliliği' ilkesinin ihlaline neden olur. Kurumsal itibar kaybı riski yüksektir.",
    businessImpactEn: "Causes violation of 'Data Privacy' principles under ISO 27001 and GDPR. High risk of corporate reputation loss.",
    remediation: "Web sunucusu konfigürasyonuna şu başlık eklenmelidir: \nStrict-Transport-Security: max-age=31536000; includeSubDomains; preload",
    remediationEn: "The following header should be added to the web server configuration: \nStrict-Transport-Security: max-age=31536000; includeSubDomains; preload",
    references: ["https://cheatsheetseries.owasp.org/cheatsheets/HTTP_Strict_Transport_Security_Cheat_Sheet.html", "https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Strict-Transport-Security"]
  },
  "csp": {
    title: "Content Security Policy (CSP) Tanımlanmamış",
    titleEn: "Content Security Policy (CSP) Not Defined",
    severity: "High",
    cvss: 7.5,
    owasp: "A03:2021-Injection",
    description: "CSP, tarayıcının hangi kaynaklardan (JS, CSS, Resim) veri yükleyebileceğini belirleyen modern bir savunma katmanıdır.",
    descriptionEn: "CSP is a modern defense layer that determines which sources (JS, CSS, Images) the browser can load data from.",
    technical: "İçerik Güvenlik Politikası (CSP) başlığı eksik. Tarayıcı, herhangi bir dış kaynaktan gelen scripti güvenilir kabul edecektir.",
    technicalEn: "Content Security Policy (CSP) header is missing. The browser will accept scripts from any external source as trusted.",
    attack: "XSS (Cross-Site Scripting) saldırılarında, saldırganın zararlı scripti sayfada başarıyla çalıştırılmasına olanak tanır.",
    attackEn: "In XSS (Cross-Site Scripting) attacks, it allows an attacker's malicious script to run successfully on the page.",
    impact: "Kullanıcı hesaplarının ele geçirilmesi, phishing sayfalarının enjekte edilmesi veya veri çalınması.",
    impactEn: "Hijacking of user accounts, injection of phishing pages, or data theft.",
    businessImpact: "Finansal kayıplar ve kullanıcı güveninin sarsılması. Veri ihlali bildirim yükümlülüğü doğurur.",
    businessImpactEn: "Financial losses and shaking of user trust. Triggers data breach notification obligations.",
    remediation: "Katı (Strict) bir CSP politikası uygulanmalıdır. Örn: Content-Security-Policy: default-src 'self'; script-src 'self' https://trusted.com;",
    remediationEn: "A strict CSP policy should be applied. e.g., Content-Security-Policy: default-src 'self'; script-src 'self' https://trusted.com;",
    references: ["https://csp-evaluator.withgoogle.com/", "https://owasp.org/www-community/controls/Content_Security_Policy"]
  },
  "options": {
    title: "Clickjacking Koruması (X-Frame-Options) Eksikliği",
    titleEn: "Missing Clickjacking Protection (X-Frame-Options)",
    severity: "Medium",
    cvss: 5.0,
    owasp: "A04:2021-Insecure Design",
    description: "X-Frame-Options, bir sitenin iframe içinde başka bir siteye gömülüp gömülemeyeceğini kontrol eder.",
    descriptionEn: "X-Frame-Options controls whether a site can be embedded in an iframe on another site.",
    technical: "X-Frame-Options veya CSP 'frame-ancestors' başlığı tanımlanmamış. Site, kötü niyetli bir sayfa içine gömülebilir.",
    technicalEn: "X-Frame-Options or CSP 'frame-ancestors' header is not defined. The site can be embedded into a malicious page.",
    attack: "Saldırgan, hedef siteyi görünmez bir katman olarak kendi sitesinin üzerine koyar ve kullanıcıyı farkında olmadan butonlara tıklamaya zorlar.",
    attackEn: "An attacker places the target site as an invisible layer over their own site and forces the user to click buttons unknowingly.",
    impact: "Kullanıcının istem dışı işlem yapması (Örn: şifre değiştirme, para transferi, silme işlemi).",
    impactEn: "User performing unintended actions (e.g., password change, fund transfer, deletion).",
    businessImpact: "İşlemsel bütünlüğün bozulması ve kullanıcı manipülasyonu.",
    businessImpactEn: "Violation of transactional integrity and user manipulation.",
    remediation: "X-Frame-Options: SAMEORIGIN başlığı eklenmelidir.",
    remediationEn: "X-Frame-Options: SAMEORIGIN header should be added.",
    references: ["https://owasp.org/www-community/attacks/Clickjacking"]
  },
  "ssl_grade_f": {
    title: "Kritik SSL/TLS Güvenlik Zafiyeti (Grade F)",
    titleEn: "Critical SSL/TLS Security Vulnerability (Grade F)",
    severity: "Critical",
    cvss: 9.8,
    owasp: "A02:2021-Cryptographic Failures",
    description: "Sertifika zincirinde veya şifreleme protokollerinde ölümcül hatalar tespit edildi.",
    descriptionEn: "Fatal errors were detected in the certificate chain or encryption protocols.",
    technical: "Desteklenen TLS sürümleri çok eski (Örn: SSLv3) veya sertifika süresi geçmiş. Modern tarayıcılar siteyi 'güvensiz' olarak işaretler.",
    technicalEn: "Supported TLS versions are very old (e.g., SSLv3) or the certificate has expired. Modern browsers will mark the site as 'insecure'.",
    attack: "Saldırganlar şifreli trafiği dakikalar içinde çözebilir veya sahte bir sertifika ile trafiği tamamen manipüle edebilir.",
    attackEn: "Attackers can decrypt encrypted traffic in minutes or completely manipulate traffic with a fake certificate.",
    impact: "Tüm iletişim kanallarının şeffaf hale gelmesi. Veri gizliliğinin SIFIRlanması.",
    impactEn: "All communication channels becoming transparent. ZERO data privacy.",
    businessImpact: "PCI-DSS uyumsuzluğu, yasal cezalar ve sitenin erişime kapatılması riski.",
    businessImpactEn: "PCI-DSS non-compliance, legal penalties, and risk of the site being taken offline.",
    remediation: "SSL sertifikasını yenileyin, TLS 1.0/1.1 desteğini kapatın ve yalnızca TLS 1.2+ sürümlerine izin verin.",
    remediationEn: "Renew the SSL certificate, disable TLS 1.0/1.1 support, and allow only TLS 1.2+ versions.",
    references: ["https://www.ssllabs.com/projects/best-practices/", "https://cheatsheetseries.owasp.org/cheatsheets/Transport_Layer_Protection_Cheat_Sheet.html"]
  },
  "xss_detected": {
    title: "Reflected Cross-Site Scripting (XSS) Tespiti",
    titleEn: "Reflected Cross-Site Scripting (XSS) Detected",
    severity: "High",
    cvss: 8.2,
    owasp: "A03:2021-Injection",
    description: "Kullanıcıdan gelen girdinin temizlenmeden HTML sayfasına yansıtılması durumudur.",
    descriptionEn: "A condition where user input is reflected onto the HTML page without being sanitized.",
    technical: "URL parametreleri veya form alanları üzerinden gönderilen script kodlarının sunucu tarafında filtrelenmediği tespit edildi.",
    technicalEn: "It was detected that script codes sent via URL parameters or form fields are not filtered on the server side.",
    attack: "Saldırgan, kurbanın tarayıcısında zararlı JavaScript kodu çalıştırarak session token bilgilerini çalabilir.",
    attackEn: "An attacker can steal session tokens by executing malicious JavaScript code in the victim's browser.",
    impact: "Kullanıcı oturumunun ele geçirilmesi ve yetkisiz işlem yapılması.",
    impactEn: "Hijacking of user sessions and unauthorized actions.",
    businessImpact: "Müşteri verilerinin gizliliğinin bozulması ve prestij kaybı.",
    businessImpactEn: "Loss of customer data privacy and prestige loss.",
    remediation: "Tüm kullanıcı girdileri uygun şekilde encode edilmeli ve 'Content-Security-Policy' uygulanmalıdır.",
    remediationEn: "All user inputs should be properly encoded and 'Content-Security-Policy' should be applied.",
    references: ["https://owasp.org/www-community/attacks/xss/"]
  },
  "sqli_error": {
    title: "SQL Enjeksiyonu Potansiyeli (Hata Tabanlı)",
    titleEn: "SQL Injection Potential (Error-Based)",
    severity: "Critical",
    cvss: 9.5,
    owasp: "A03:2021-Injection",
    description: "Veritabanı hatalarının son kullanıcıya gösterilmesi, veritabanı yapısı hakkında bilgi sızmasına neden olur.",
    descriptionEn: "Exposing database errors to the end user causes leakage of information about the database structure.",
    technical: "Özel karakterler (tek tırnak vb.) gönderildiğinde sunucunun ham SQL hata mesajları döndürdüğü görüldü.",
    technicalEn: "It was observed that the server returns raw SQL error messages when special characters (single quotes, etc.) are sent.",
    attack: "Saldırgan bu hataları kullanarak veritabanı tablolarını, sütun isimlerini ve nihayetinde tüm verileri çekebilir.",
    attackEn: "An attacker can use these errors to extract database tables, column names, and ultimately all data.",
    impact: "Tüm veritabanının sızdırılması (Massive Data Leak).",
    impactEn: "Leakage of the entire database (Massive Data Leak).",
    businessImpact: "Veri sızıntısı bildirimleri, büyük finansal cezalar ve iş durması.",
    businessImpactEn: "Data breach notifications, heavy financial fines, and business interruption.",
    remediation: "Hata mesajları gizlenmeli ve 'Prepared Statements' kullanılmalıdır.",
    remediationEn: "Error messages should be hidden and 'Prepared Statements' should be used.",
    references: ["https://owasp.org/www-community/attacks/SQL_Injection"]
  },
  "open_database": {
    title: "Açık Veritabanı Portu veya Paneli",
    titleEn: "Open Database Port or Panel",
    severity: "Critical",
    cvss: 10.0,
    owasp: "A01:2021-Broken Access Control",
    description: "Veritabanı yönetim arayüzünün veya portunun internete açık olması durumudur.",
    descriptionEn: "A condition where the database management interface or port is exposed to the internet.",
    technical: "3306 (MySQL), 5432 (PostgreSQL) veya /phpmyadmin gibi yolların erişilebilir olduğu tespit edildi.",
    technicalEn: "It was detected that paths like 3306 (MySQL), 5432 (PostgreSQL), or /phpmyadmin are accessible.",
    attack: "Saldırganlar brute-force veya bilinen zafiyetler ile veritabanına doğrudan erişim sağlayabilir.",
    attackEn: "Attackers can gain direct access to the database via brute-force or known vulnerabilities.",
    impact: "Verilerin çalınması, silinmesi veya fidye yazılımı (Ransomware) saldırısı.",
    impactEn: "Data theft, deletion, or ransomware attack.",
    businessImpact: "Kritik veri kaybı ve kurumsal operasyonların çökmesi.",
    businessImpactEn: "Critical data loss and collapse of corporate operations.",
    remediation: "Veritabanı portları dış dünyaya kapatılmalı ve sadece yetkili IP'lere izin verilmelidir.",
    remediationEn: "Database ports should be closed to the outside world and only authorized IPs should be allowed.",
    references: ["https://cwe.mitre.org/data/definitions/668.html"]
  },
  "exposed_sensitive_files": {
    title: "Kritik Sistem Dosyası İfşası (.env, .git)",
    titleEn: "Critical System File Exposure (.env, .git)",
    severity: "Critical",
    cvss: 9.9,
    owasp: "A01:2021-Broken Access Control",
    description: "Sunucu üzerindeki gizli konfigürasyon dosyalarına veya kaynak kod geçmişine doğrudan erişilebilir olması durumudur.",
    descriptionEn: "Direct accessibility of hidden configuration files or source code history on the server.",
    technical: "Hedef domain üzerinde yapılan path probes sonucunda /.env veya /.git/config gibi dosyalara 200 OK yanıtı ile ulaşılabildiği tespit edildi.",
    technicalEn: "Path probes on the target domain revealed that files like /.env or /.git/config can be reached with a 200 OK response.",
    attack: "Saldırganlar .env dosyasını indirerek veritabanı şifrelerini, API anahtarlarını ve gizli sertifikaları saniyeler içinde ele geçirebilir.",
    attackEn: "Attackers can download the .env file and hijack database passwords, API keys, and secret certificates in seconds.",
    impact: "Tüm sistemin tam kontrolünün (Total Compromise) saldırganın eline geçmesi.",
    impactEn: "The attacker gaining full control of the entire system (Total Compromise).",
    businessImpact: "Müşteri verilerinin toplu sızıntısı, kurumsal iflas riski ve KVKK kapsamında en ağır cezalar.",
    businessImpactEn: "Mass leak of customer data, risk of corporate bankruptcy, and heaviest fines under GDPR.",
    remediation: "Nginx/Apache konfigürasyonunda nokta ile başlayan dosyalara erişim yasaklanmalı veya bu dosyalar web root dizini dışına çıkarılmalıdır.",
    remediationEn: "Access to files starting with a dot should be prohibited in Nginx/Apache configuration, or these files should be moved outside the web root directory.",
    references: ["https://cwe.mitre.org/data/definitions/538.html", "https://owasp.org/www-project-top-ten/2017/A6_2017-Security_Misconfiguration"]
  },
  "insecure_http": {
    title: "Hassas Veri İletimi Üzerinden Güvensiz Protokol (HTTP)",
    titleEn: "Insecure Protocol (HTTP) Over Sensitive Data Transmission",
    severity: "High",
    cvss: 7.5,
    owasp: "A02:2021-Cryptographic Failures",
    description: "Sitenin HTTPS yerine şifresiz HTTP protokolü üzerinden erişilebilir olması durumudur.",
    descriptionEn: "A condition where the site is accessible via unencrypted HTTP instead of HTTPS.",
    technical: "Sunucu 80 portu üzerinden istek kabul etmektedir ve zorunlu bir HTTPS yönlendirmesi tespit edilememiştir.",
    technicalEn: "The server accepts requests over port 80, and no mandatory HTTPS redirection was detected.",
    attack: "Saldırganlar şifresiz ağlarda (Ortadaki Adam saldırısı - MitM) kullanıcı verilerini kolayca koklayabilir.",
    attackEn: "Attackers can easily sniff user data on unencrypted networks (Man-in-the-Middle attack - MitM).",
    impact: "Oturum çerezlerinin, şifrelerin ve kişisel verilerin açık metin olarak ele geçirilmesi.",
    impactEn: "Hijacking of session cookies, passwords, and personal data as cleartext.",
    businessImpact: "Müşteri güveninin kaybı ve KVKK veri güvenliği ihlali.",
    businessImpactEn: "Loss of customer trust and GDPR data security violation.",
    remediation: "Sunucuda 443 (HTTPS) yapılandırılmalı ve tüm HTTP istekleri 301 yönlendirmesi ile HTTPS'ye çekilmelidir.",
    remediationEn: "Configure 443 (HTTPS) on the server and redirect all HTTP requests to HTTPS via 301.",
    references: ["https://owasp.org/www-project-top-ten/2017/A3_2017-Sensitive_Data_Exposure"]
  },
  "spf_missing": {
    title: "SPF (Sender Policy Framework) Kaydı Eksikliği",
    titleEn: "Missing SPF (Sender Policy Framework) Record",
    severity: "High",
    cvss: 6.5,
    owasp: "A04:2021-Insecure Design",
    description: "Domain üzerinden kimlerin e-posta gönderebileceğini belirten DNS kaydının bulunmamasıdır.",
    descriptionEn: "Absence of a DNS record indicating who is authorized to send emails from the domain.",
    technical: "Hedef domain için geçerli bir SPF TXT kaydı bulunamadı.",
    technicalEn: "No valid SPF TXT record was found for the target domain.",
    attack: "Saldırganlar, kurum adını kullanarak sahte e-postalar (Phishing/Spoofing) göndererek çalışanları veya müşterileri kandırabilir.",
    attackEn: "Attackers can send fake emails (Phishing/Spoofing) using the company name to deceive employees or customers.",
    impact: "Alan adı itibarının zedelenmesi ve yüksek başarılı phishing saldırıları.",
    impactEn: "Damage to domain reputation and highly successful phishing attacks.",
    businessImpact: "Marka kimlik hırsızlığı ve finansal dolandırıcılık riski.",
    businessImpactEn: "Brand identity theft and risk of financial fraud.",
    remediation: "DNS ayarlarına 'v=spf1 include:_spf.google.com ~all' benzeri uygun bir SPF kaydı eklenmelidir.",
    remediationEn: "A suitable SPF record like 'v=spf1 include:_spf.google.com ~all' should be added to DNS settings.",
    references: ["https://en.wikipedia.org/wiki/Sender_Policy_Framework"]
  },
  "dmarc_missing": {
    title: "DMARC Politikası Yapılandırılmamış",
    titleEn: "DMARC Policy Not Configured",
    severity: "High",
    cvss: 6.0,
    owasp: "A04:2021-Insecure Design",
    description: "E-posta güvenliğini artıran DMARC (Domain-based Message Authentication) kaydının eksik olmasıdır.",
    descriptionEn: "Missing DMARC (Domain-based Message Authentication) record that enhances email security.",
    technical: "DNS sorgusunda '_dmarc' alt alan adı için herhangi bir politika kaydı tespit edilemedi.",
    technicalEn: "No policy record was detected for the '_dmarc' subdomain in the DNS query.",
    attack: "SPF ve DKIM doğrulaması geçemeyen sahte e-postaların nasıl işleneceğine dair bir kural olmadığı için saldırılar engellenemez.",
    attackEn: "Since there is no rule on how to handle fake emails that fail SPF and DKIM verification, attacks cannot be prevented.",
    impact: "Domain üzerinden yapılan sahte e-posta gönderimlerinin alıcı sunucular tarafından kabul edilmesi.",
    impactEn: "Recipient servers accepting fake emails sent via the domain.",
    businessImpact: "Kurumsal iletişim kanallarının güvensiz hale gelmesi.",
    businessImpactEn: "Corporate communication channels becoming insecure.",
    remediation: "DNS ayarlarına en azından izleme modunda bir DMARC kaydı eklenmelidir (v=DMARC1; p=none;).",
    remediationEn: "A DMARC record should be added to DNS settings at least in monitoring mode (v=DMARC1; p=none;).",
    references: ["https://dmarc.org/"]
  }
};
