import React from 'react';
import { Database, Shield, ShieldCheck, Terminal, QrCode, CheckCircle } from 'lucide-react';
import { QRCodeSVG } from 'qrcode.react';
import { Page, DataItem } from './FullReportComponents';
import { GLOBAL_ISO_MAPPING } from './FullReportUtils';


/**
 * @component LastPages
 * @description Raporun teknik kanıt (Evidence), uyumluluk (Compliance) ve yasal sayfalarını yönetir.
 */
export const LastPages = ({ auditData, t, layout, totalPages, siteName, metadata }) => {
   const isoMapping = GLOBAL_ISO_MAPPING;
   const clauses = auditData.disclaimer?.clauses || [];

   const dumpText = JSON.stringify(auditData || {}, null, 2);
   const dumpChunks = Array.from({ length: Math.ceil(dumpText.length / 1200) }, (_, i) =>
     dumpText.slice(i * 1200, i * 1200 + 1200)
   );

   return (
     <>
       {/* DYNAMIC TECHNICAL DUMP CHUNKS */}
       {dumpChunks.map((chunk, idx) => (
          <Page key={`dump-${idx}`} pageNum={(layout?.dump1 ?? 30) + idx} totalPages={totalPages} title={`${t.items?.dumpTitle} — PART ${idx + 1}`} t={t}>
             <div className="space-y-6">
                {idx === 0 && (
                   <div className="bg-blue-50 border-2 border-blue-100 p-6 rounded-[2.5rem] mb-4">
                      <div className="flex items-center gap-4 mb-4">
                         <Database size={32} className="text-blue-900" />
                         <h4 className="text-xl font-black text-blue-900 uppercase tracking-tighter text-left">{t.items?.dumpTitle}</h4>
                      </div>
                      <p className="text-[10px] font-bold text-blue-900/60 leading-relaxed uppercase tracking-widest text-left">
                         {t.items?.dumpDesc}
                      </p>
                   </div>
                )}

                <div className="space-y-8">
                   <section className="bg-slate-50 border border-slate-200 rounded-[2rem] p-8 shadow-sm relative overflow-hidden group">
                      <div className="absolute top-0 right-0 p-4 opacity-5 group-hover:opacity-10 transition-opacity">
                         <Terminal size={100} className="text-blue-600" />
                      </div>
                      <h5 className="text-[10px] font-black text-blue-600 uppercase tracking-widest mb-4">DUMP PART_{idx + 1}.LOG</h5>
                      <pre className="font-mono text-[7px] text-slate-500 leading-tight max-h-[460px] overflow-hidden text-left whitespace-pre-wrap break-all">
                         {chunk}
                      </pre>
                   </section>
                </div>
             </div>
          </Page>
       ))}

       {/* LEGAL PAGE */}
       <Page pageNum={layout?.legal} totalPages={totalPages} title={t.items?.tocLegalDisclaimer} t={t}>
          <div className="space-y-6 text-left">
             {clauses.map((c, i) => (
                <div key={i} className="border-b border-slate-100 pb-4">
                   <h5 className="font-black text-xs text-slate-900 mb-2 uppercase tracking-tighter">{c.heading}</h5>
                   <p className="text-[10px] text-slate-500 leading-relaxed font-bold text-justify">{c.text}</p>
                </div>
             ))}
             <div className="mt-12 p-8 bg-slate-50 rounded-[2rem] border border-slate-100 italic text-[10px] text-slate-400 font-bold leading-relaxed">
                {t.reportTitle?.includes('MÜHENDİSLİĞİ')
                  ? `"Bu rapor ALFA YAPAY ZEKA Teknolojileri tarafından AI destekli olarak gerçek şartlarda üretilmiştir. Herhangi bir düzenleme veya manipülasyon raporun kurguladığı dijital hash imzasını (Integrity Hash) geçersiz kılar. Raporun tüm sayfaları dijital olarak şifrelenmiştir."`
                  : `"This report has been generated by ALFA AI Technologies with AI support under real conditions. Any modification or manipulation invalidates the digital integrity hash signature of the report. All pages are digitally encrypted."`}
             </div>
          </div>
       </Page>

       {/* MULTI-STANDARD COMPLIANCE MATRIX */}
       <Page pageNum={layout?.isoMapping} totalPages={totalPages} title={t.reportTitle?.includes('MÜHENDİSLİĞİ') ? 'ÇOK BOYUTLU UYUMLULUK MATRİSİ' : 'MULTI-STANDARD COMPLIANCE MATRIX'} t={t}>
          <div className="space-y-8 text-left">
             <div className="bg-emerald-50/50 border border-emerald-100 p-8 rounded-[2.5rem] mb-4">
                <div className="flex items-center gap-4 mb-4">
                   <Shield size={32} className="text-emerald-900" />
                   <h4 className="text-xl font-black text-emerald-900 uppercase tracking-tighter">
                     {t.reportTitle?.includes('MÜHENDİSLİĞİ') ? 'GLOBAL UYUMLULUK VE RİSK MATRİSİ' : 'GLOBAL COMPLIANCE & RISK MATRIX'}
                   </h4>
                </div>
                <p className="text-[10px] font-bold text-emerald-900/60 leading-relaxed uppercase tracking-widest">
                   {t.reportTitle?.includes('MÜHENDİSLİĞİ') 
                     ? 'ALFA X-RAY V3 DENETİM MODÜLLERİNİN ULUSLARARASI SİBER GÜVENLİK VE BİLGİ TEKNOLOJİLERİ YÖNETİŞİM STANDARTLARI İLE ÇAPRAZ EŞLEŞTİRMESİ.'
                     : 'CROSS-MAPPING OF ALFA X-RAY V3 AUDIT MODULES WITH INTERNATIONAL CYBERSECURITY AND IT GOVERNANCE STANDARDS.'}
                </p>
             </div>

             <div className="bg-white border-2 border-slate-100 rounded-[2.5rem] overflow-hidden shadow-sm">
                <table className="w-full text-[7.5px] table-fixed">
                   <thead className="bg-slate-50 text-slate-900 font-black uppercase tracking-widest border-b border-slate-200">
                      <tr>
                         <th className="px-3 py-3 text-left w-[18%]">MODÜL / BÖLÜM</th>
                         <th className="px-2 py-3 text-center w-[12%]">ISO 27001</th>
                         <th className="px-2 py-3 text-center w-[12%]">ISO 27002</th>
                         <th className="px-2 py-3 text-center w-[12%] font-black text-blue-700">ISO 27005</th>
                         <th className="px-2 py-3 text-center w-[12%]">ITIL v4</th>
                         <th className="px-2 py-3 text-center w-[12%]">COBIT</th>
                         <th className="px-3 py-3 text-left w-[22%]">AÇIKLAMA (SCOPE)</th>
                      </tr>
                   </thead>
                   <tbody>
                      {Object.entries(isoMapping || {}).map(([key, value], i) => {
                         const sectionTitle = t.sections?.[key] || '';
                         const sectionNum = sectionTitle.indexOf(':') !== -1 ? sectionTitle.split(':')[0].trim() : sectionTitle;
                         
                         return (
                            <tr key={key} className={`border-b border-slate-100 ${i % 2 === 0 ? 'bg-white' : 'bg-slate-50/30'}`}>
                               <td className="px-3 py-2 font-black text-slate-800 uppercase tracking-tighter truncate">
                                  {key.toUpperCase()} <span className="text-slate-400 font-bold text-[6px]">({sectionNum})</span>
                               </td>
                               <td className="px-2 py-2 font-mono font-black text-emerald-700 text-center">{value.iso27001}</td>
                               <td className="px-2 py-2 font-mono font-bold text-slate-600 text-center">{value.iso27002}</td>
                               <td className="px-2 py-2 font-mono font-black text-blue-700 text-center bg-blue-50/30">{value.iso27005}</td>
                               <td className="px-2 py-2 font-mono font-bold text-indigo-600 text-center">{value.itil}</td>
                               <td className="px-2 py-2 font-mono font-bold text-amber-600 text-center">{value.cobit}</td>
                               <td className="px-3 py-2 font-bold text-slate-400 uppercase text-[7px] leading-tight truncate">{value.name}</td>
                            </tr>
                         );
                      })}
                   </tbody>
                </table>
             </div>
             <p className="text-[8px] text-slate-400 italic text-center font-bold uppercase tracking-widest">
                {t.reportTitle?.includes('MÜHENDİSLİĞİ')
                  ? '* BU MATRİS ISO 27005:2022 RİSK YÖNETİMİ ODAKLI ÇAPRAZ REFERANS TABLOSUDUR.'
                  : '* THIS MATRIX IS A CROSS-REFERENCE TABLE FOCUSED ON ISO 27005:2022 RISK MANAGEMENT.'}
             </p>
          </div>
       </Page>

       {/* FINAL APPROVAL PAGE */}
       <Page pageNum={layout?.final} totalPages={totalPages} title={t.items?.final} t={t}>
         <div className="h-full flex flex-col justify-between pt-12 pb-6">
            <div className="space-y-[40px]">
               <p className="text-lg text-gray-600 leading-relaxed italic border-l-4 border-slate-200 pl-6 pr-12 text-left">
                  {t.signatureDisclaimer}
               </p>
     
               <div className="bg-slate-50 border-2 border-dashed border-slate-200 p-8 rounded-[2rem] space-y-4">
                  <h4 className="text-[10px] font-black text-slate-400 uppercase tracking-[0.3em] text-left">{t.items?.integrityTitle}</h4>
                  <div className="flex items-center gap-8">
                     <ShieldCheck size={40} className="text-green-600" />
                     <div className="font-mono text-[9px] text-slate-500 uppercase leading-loose text-left">
                        <p>{t.items?.engineLabel}: ALFA-XRAY-V3.0 (SECURITY INTELLIGENCE CORE)</p>
                        <p>{t.items?.targetLabel}: HTTPS://WWW.{siteName.toUpperCase()}</p>
                        <p>{t.items?.hashLabel}: {metadata.integrityHash}</p>
                        <p>{t.items?.dateLabel}: {metadata.isoDate}</p>
                     </div>
                  </div>
               </div>
               
               <div className="flex items-center justify-start mt-4">
                  <div className="bg-white border-2 border-slate-200 p-4 rounded-[1.5rem] shadow-sm flex items-center justify-center relative group">
                     <QRCodeSVG 
                       value={`TGT: www.${siteName.toLowerCase()}\nHASH: ${metadata.integrityHash.slice(0, 20)}...\nDATE: ${metadata.isoDate}`}
                       size={120}
                       level={"H"}
                       includeMargin={true}
                     />
                  </div>
               </div>
            </div>
     
            <div className="flex justify-end -mt-24 pr-12">
               <div className="text-right flex flex-col items-end">
                  <div className="relative inline-block z-10 -mb-12 mr-6">
                     <img src="/CLEAN_SIGNATURE_EG_FINAL.png" alt="Signature" className="h-[120px] mix-blend-multiply brightness-90 contrast-125" />
                  </div>
                  <div className="space-y-1 relative z-0 pt-4 min-w-[250px]">
                     <p className="text-3xl font-black tracking-tighter leading-none text-slate-900">{t.signatureName}</p>
                     <p className="text-base font-bold text-primary mt-1">{t.signatureHead}</p>
                     <p className="text-[10px] font-black text-slate-300 uppercase tracking-[0.2em] mt-1">{t.signatureUnit}</p>
                  </div>
               </div>
            </div>
            
            <div className="pt-4 flex justify-between items-end">
               <div className="space-y-1 text-left">
                  <p className="text-[8px] text-slate-300 font-mono uppercase tracking-[0.2em]">DOSS_ID: {metadata.dossierId}</p>
                  <p className="text-[8px] text-slate-300 font-mono uppercase tracking-[0.2em]">{t.items?.nodeLabel}: ALFA-PRIMARY-XRAY-TX-CORE</p>
               </div>
               <div className="px-3 py-1 bg-slate-50 border rounded text-[8px] font-black text-slate-400 uppercase tracking-widest">
                  {t.items?.endOfDossier} — PAGE {totalPages}
               </div>
            </div>
         </div>
       </Page>
     </>
   );
};
